spring:
  jpa:
    show-sql: true

  datasource:
    url: 'jdbc:postgresql://localhost:5432/general_ledger?sslmode=prefer'
    username: postgres
    password: postgres

hmpps-auth:
  url: "http://localhost:8090/auth"